{% set name = "cookiecutter-data-science" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/cookiecutter_data_science-{{ version }}.tar.gz
  sha256: d32359d0494b67c847c79f63b8af87326f21f83b09882da6d3430b31970cf46e

build:
  entry_points:
    - ccds = ccds.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - click
    - cookiecutter

test:
  commands:
    - pip check
    - ccds --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/drivendataorg/cookiecutter-data-science
  doc_url: https://cookiecutter-data-science.drivendata.org/
  summary: A logical, reasonably standardized but flexible project structure for doing and sharing data science work.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jayqi
    - thewchan
